<script setup lang="ts">
import { Sparkles, Star, Play } from 'lucide-react';
import type { Movie } from '../types';

const props = defineProps<{
  viewHistory: Movie[];
  allMovies: Movie[];
}>();

const emit = defineEmits<{
  (e: 'selectMovie', movie: Movie): void;
}>();

const getRecommendations = () => {
  const historyCategories = props.viewHistory.map(m => m.category);
  const favoriteCategory = Object.entries(
    historyCategories.reduce((acc, cat) => ({ ...acc, [cat]: (acc[cat] || 0) + 1 }), {} as Record<string, number>)
  ).sort((a, b) => b[1] - a[1])[0]?.[0];

  return props.allMovies
    .filter(m => !props.viewHistory.find(h => h.id === m.id))
    .filter(m => m.category === favoriteCategory || parseFloat(m.rating) > 8.5)
    .slice(0, 4);
};

const recommendations = getRecommendations();
</script>

<template>
  <section class="max-w-7xl mx-auto px-4 py-20 bg-primary/5 rounded-[48px] my-10 border border-primary/10 relative overflow-hidden">
    <div class="absolute top-0 right-0 w-96 h-96 bg-primary/10 blur-[100px] -mr-48 -mt-48 rounded-full" />
    
    <div class="relative z-10">
      <div class="flex items-center gap-4 mb-12">
        <div class="w-12 h-12 bg-primary rounded-2xl flex items-center justify-center">
          <Sparkles class="text-white" :size="24" />
        </div>
        <div>
          <span class="mono-label !text-primary block mb-1">Generated by AI</span>
          <h2 class="text-3xl md:text-5xl font-black italic uppercase tracking-tighter">Iyo <span class="text-primary">Nyazo</span></h2>
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div 
          v-for="(movie, idx) in recommendations" 
          :key="movie.id"
          class="recommendation-card"
          @click="emit('selectMovie', movie)"
        >
          <div class="group cursor-pointer">
            <div class="relative aspect-[16/9] rounded-3xl overflow-hidden mb-6 border border-white/5 transition-all group-hover:border-primary">
              <img :src="movie.poster" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" />
              <div class="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent opacity-60" />
              <div class="absolute bottom-4 left-4">
                <div class="flex items-center gap-2 px-3 py-1 bg-primary text-white rounded-lg text-[10px] font-black uppercase italic italic-tighter">
                  <Star :size="10" fill="currentColor" />
                  {{ movie.rating }}
                </div>
              </div>
              <div class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                <Play :size="40" class="text-white bg-primary p-3 rounded-full shadow-premium" fill="currentColor" />
              </div>
            </div>
            <h4 class="text-lg font-black italic uppercase tracking-tighter truncate group-hover:text-primary transition-colors">
              {{ movie.title }}
            </h4>
            <p class="text-[10px] font-bold text-white/30 uppercase tracking-widest mt-1">{{ movie.category }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.recommendation-card {
  transition: transform 0.3s ease;
}
.recommendation-card:hover {
  transform: translateY(-5px);
}
</style>
